version: '3'
volumes:
  postgres-data:
  pgadmin-data:

services:
  postgres:
    container_name: Postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: yfoo
      POSTGRES_PASSWORD: yfoo
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    container_name: PgAdmin
    image: dpage/pgadmin4
    ports:
      - "80:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: yfoo@yfoo.com
      PGADMIN_DEFAULT_PASSWORD: yfoo
    depends_on:
      - postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin

# sudo docker-compose up